// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package qxTypes

type AllowCreateModelSasFile struct {
	UploadType   int32  `json:"uploadType,optional"`
	Key          string `json:"key"`
	Bucket       string `json:"bucket"`
	CollectionId uint32 `json:"collectionId,optional"`
	FileName     string `json:"fileName"`
	FileSize     int64  `json:"fileSize"`
	MimeType     string `json:"mimeType"`
	Remark       string `json:"remark,optional"`
	UploadDir    string `json:"uploadDir,optional"`
}

type AllowCreateModelSasFileWithFrontedUpload struct {
	Key              string `json:"key"`
	Bucket           string `json:"bucket"`
	FileName         string `json:"fileName"`
	FileSize         int64  `json:"fileSize"`
	MimeType         string `json:"mimeType"`
	CollectionId     uint32 `json:"collectionId,optional"`
	Remark           string `json:"remark,optional"`
	UploadDir        string `json:"uploadDir,optional"`
	IsMultipleTenant bool   `json:"isMultipleTenant,optional"`
}

type AllowUpdateModelSasFile struct {
	Id               uint32   `json:"id"`
	CollectionId     uint32   `json:"collectionId,optional"`
	FileName         string   `json:"fileName,optional"`
	Cover            string   `json:"cover,optional"`
	AlternativeCover []string `json:"alternativeCover,optional"`
	Width            int32    `json:"width,optional"`
	Height           int32    `json:"height,optional"`
	UploadSignBody   string   `json:"uploadSignBody,optional"`
}

type AllowUpdateStatusModelSasFile struct {
	Id               uint32   `json:"id"`
	Status           int32    `json:"status"`
	AlternativeCover []string `json:"alternativeCover,optional"`
	Width            int32    `json:"width,optional"`
	Height           int32    `json:"height,optional"`
	UploadSignBody   string   `json:"uploadSignBody,optional"`
}

type ApiCaptchaGenerateReq struct {
	Key       string  `json:"key,optional"`
	DotCount  int32   `json:"dotCount,optional"`
	MaxSkew   float64 `json:"maxSkew,optional"`
	KeyLong   int32   `json:"keyLong,optional"`
	ImgWidth  int32   `json:"imgWidth,optional"`
	ImgHeight int32   `json:"imgHeight,optional"`
}

type ApiCaptchaGenerateResp struct {
	Code      int32                      `json:"code"`
	Msg       string                     `json:"msg"`
	Path      string                     `json:"path"`
	RequestID string                     `json:"requestId"`
	Data      ApiCaptchaGenerateRespData `json:"data"`
}

type ApiCaptchaGenerateRespData struct {
	Key     string `json:"key,omitempty"`
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type ApiRefreshReq struct {
	AccessKey    string `json:"accessKey"`
	RefreshToken string `json:"refreshToken"`
}

type ApiRefreshResp struct {
	Code      int32           `json:"code"`
	Msg       string          `json:"msg"`
	Path      string          `json:"path"`
	RequestID string          `json:"requestId"`
	Data      SignResultModel `json:"data"`
}

type ApiSignReq struct {
	AccessKey    string `json:"accessKey"`
	AccessSecret string `json:"accessSecret"`
}

type ApiSignResp struct {
	Code      int32           `json:"code"`
	Msg       string          `json:"msg"`
	Path      string          `json:"path"`
	RequestID string          `json:"requestId"`
	Data      SignResultModel `json:"data"`
}

type ApiSmsSendReq struct {
	Key    string   `json:"key"`
	Mobile string   `json:"mobile"`
	Params []string `json:"params,optional"`
}

type ApiSmsSendResp struct {
	Code      int32  `json:"code"`
	Msg       string `json:"msg"`
	Path      string `json:"path"`
	RequestID string `json:"requestId"`
	Data      string `json:"data"`
}

type ApiSmsSendRespData struct {
	RequestID string `json:"requestId"`
}

type BootstrapReq struct {
	AccessKey    string `form:"accessKey"`
	AccessSecret string `form:"accessSecret"`
}

type BootstrapResp struct {
	Code      int32  `json:"code"`
	Msg       string `json:"msg"`
	Path      string `json:"path"`
	RequestID string `json:"requestId"`
	Data      string `json:"data"`
}

type CallbackAliyuncsOssFrontendUploadReq struct {
	Filename string `form:"filename,optional"`
	Height   int32  `form:"height,optional"`
	Width    int32  `form:"width,optional"`
	MimeType string `form:"mimeType,optional"`
	Size     int64  `form:"size,optional"`
	UUID     string `path:"uuid,optional"`
	UniqueId string `path:"uniqueId,optional"`
}

type CallbackAliyuncsOssFrontendUploadResp struct {
	Code      int32                                     `json:"code"`
	Msg       string                                    `json:"msg"`
	RequestID string                                    `json:"requestId"`
	Path      string                                    `json:"path"`
	Data      CallbackAliyuncsOssFrontendUploadRespData `json:"data"`
}

type CallbackAliyuncsOssFrontendUploadRespData struct {
	FileName    string `json:"filename"`
	Size        int64  `json:"size"`
	MineType    string `json:"mimeType"`
	Height      int64  `json:"height"`
	Width       int64  `json:"width"`
	ExternalUrl string `json:"externalUrl"`
	Cover       string `json:"cover"`
}

type HealthzResp struct {
	Code      int32  `json:"code"`
	Msg       string `json:"msg"`
	Path      string `json:"path"`
	RequestID string `json:"requestId"`
	Data      string `json:"data"`
}

type ModelSasFile struct {
	Id              uint32   `json:"id"`
	CreatedAtUnix   int64    `json:"createdAtUnix"`
	UpdatedAtUnix   int64    `json:"updatedAtUnix"`
	TenantId        uint32   `json:"tenantId"`     // 租户ID
	CollectionId    uint32   `json:"collectionId"` // 文件集合ID
	Key             string   `json:"key"`          // 配置的key
	UploadType      int32    `json:"uploadType"`
	Bucket          string   `json:"bucket"`
	Endpoint        string   `json:"endpoint"`
	FileType        int32    `json:"fileType"`
	Uuid            string   `json:"uuid"`
	FileName        string   `json:"fileName"`
	FileExt         string   `json:"fileExt"`
	FileSize        int64    `json:"fileSize"`
	FormatName      string   `json:"formatName"`
	Remark          string   `json:"remark"`
	Path            string   `json:"path"`
	ExternalPath    string   `json:"externalPath"`
	MimeType        string   `json:"mimeType"`
	Width           int32    `json:"width"`
	Height          int32    `json:"height"`
	Cover           string   `json:"cover"`
	AlternativeCove []string `json:"alternativeCover"`
	UploadSignBody  string   `json:"uploadSignBody"`
}

type PingReq struct {
	Ping string `form:"ping"`
}

type PingResp struct {
	Code      int32  `json:"code"`
	Msg       string `json:"msg"`
	Path      string `json:"path"`
	RequestID string `json:"requestId"`
	Data      string `json:"data"`
}

type SasFileApiCreateResp struct {
	Code      int32               `json:"code"`
	Msg       string              `json:"msg"`
	RequestID string              `json:"requestId"`
	Path      string              `json:"path"`
	Data      SasFileApiJsonIdReq `json:"data"`
}

type SasFileApiCreateWithOssV4FrontUploadResp struct {
	Code      int32                                        `json:"code"`
	Msg       string                                       `json:"msg"`
	Path      string                                       `json:"path"`
	RequestID string                                       `json:"requestId"`
	Data      SasFileApiCreateWithOssV4FrontUploadRespData `json:"data"`
}

type SasFileApiCreateWithOssV4FrontUploadRespData struct {
	Id      uint32 `json:"id"`
	SignUrl string `json:"signUrl"`
}

type SasFileApiFormIdReq struct {
	Id uint32 `form:"id"`
}

type SasFileApiFormIdsReq struct {
	Ids []uint32 `form:"id"`
}

type SasFileApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type SasFileApiOKResp struct {
	Code      int32  `json:"code"`
	Msg       string `json:"msg"`
	RequestID string `json:"requestId"`
	Path      string `json:"path"`
	Data      string `json:"data"`
}

type SasFileCommonCreateWithOssFrontUploadResp struct {
	Code      int32                                         `json:"code"`
	Msg       string                                        `json:"msg"`
	Path      string                                        `json:"path"`
	RequestID string                                        `json:"requestId"`
	Data      SasFileCommonCreateWithOssFrontUploadRespData `json:"data"`
}

type SasFileCommonCreateWithOssFrontUploadRespData struct {
	Id             uint32 `json:"id"`
	Key            string `json:"key"`
	OSSAccessKeyId string `json:"ossAccessKeyId"`
	Policy         string `json:"policy"`
	Signature      string `json:"signature"`
	Callback       string `json:"callback"`
	IsCallback     bool   `json:"isCallback"`
	Host           string `json:"host"`
	Domain         string `json:"domain"`
}

type SasFileCommonQueryListResp struct {
	Code      int32                          `json:"code"`
	Msg       string                         `json:"msg"`
	Path      string                         `json:"path"`
	RequestID string                         `json:"requestId"`
	Data      SasFileCommonQueryListRespData `json:"data"`
}

type SasFileCommonQueryListRespData struct {
	List     []ModelSasFile `json:"list"`
	Total    int64          `json:"total"`
	Page     int32          `json:"page"`
	PageSize int32          `json:"pageSize"`
}

type SasFileCommonQueryResp struct {
	Code      int32        `json:"code"`
	Msg       string       `json:"msg"`
	Path      string       `json:"path"`
	RequestID string       `json:"requestId"`
	Data      ModelSasFile `json:"data"`
}

type SasFileCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"pageSize,optional"`
	StartCreatedAt int64  `json:"startCreatedAt,optional"`
	EndCreatedAt   int64  `json:"endCreatedAt,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int32  `json:"status,optional"`
}

type SignResultModel struct {
	AccessToken      string `json:"accessToken"`
	AccessExpiresAt  int64  `json:"accessExpiresAt"`
	RefreshToken     string `json:"refreshToken"`
	RefreshExpiresAt int64  `json:"refreshExpiresAt"`
}

type TestReq struct {
	Msg string `json:"msg"`
}

type TestResp struct {
	Code      int32  `json:"code"`
	Msg       string `json:"msg"`
	Path      string `json:"path"`
	RequestID string `json:"requestId"`
	Data      string `json:"data"`
}
